#!/system/bin/sh
#
# Script to start "om" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/om.jar
exec app_process $base/bin com.android.commands.om.Om "$@"
